name: CI/CD pipeline

on: push

jobs:
  backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: testdb
        ports:
          - 5432:5432

    env:
      JWT_SECRET_KEY: 5OQ1ZE9FJiP0d3PKTnOT
      DATABASE_URL: postgresql://test:password123@localhost:5432/testdb?schema=public

    steps:
      - name: Notify Trigger
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event on branch ${{ github.ref }}."

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Cache Dependencies
        uses: actions/cache@v2
        id: backend-npm-cache
        with:
          path: "node_modules"
          key: client-npm-${{ hashFiles('package.json') }}

      - name: Install Dependencies
        run: npm install
        if: steps.backend-npm-cache.outputs.cache-hit != 'true'

      - name: Run Linter
        run: npm run lint

      - name: Run Typecheck
        run: npm run typecheck

      - name: Execute Migrations
        run: npx prisma migrate deploy

      - name: Run Test
        run: npm run test

      - name: Display Job Status
        run: echo "🍏 This job's status is ${{ job.status }}."
